translib/app_interface.go, translib/subscribe.go, translib/translib.go, translib/version.go
- Go formatting changes
- Subscribe API standardized to take structures as input and output (This is a dependency for REST and gNMI PRs)
- Action(RPC ) API body (Implementation will be done in future PRs (This is a dependency for REST and gNMI PRs)
- REST query parameters field support in translib (This is a dependency for REST)
- Changes to have write disabled for DB operation (Need to integrate with DB access layer once that PR comes in)
- Versioning bare minimum actual support will come in a separate PR (This is a dependency for REST and gNMI PRs)
- Static analysis tool fixes
=> Translib phase I changes

cvl/cvl_test.go, cvl/internal/util/util.go, translib/Makefile, translib/acl_app_test.go, translib/api_tests_app.go, translib/app_utils_test.go, translib/transformer/transformer.go
**- Why I did it**
There are few issues in cvl and translib go test code.
**- How I did it**
1\) Fixed compilation is translib test code. Temporarily disabled ACL test codes from translib test since there are too many errors in it. Moved all common utility code in ACL test file into a new common file (app_utils_test.go).
2\) Fixed the failures in cvl test code.
3\) Added a new app module api_tests_app.go which provides dummy implementations of all app interface APIs for paths starting with `/api-tests:`. Errors can be simulated by including token `/error/` in the path. This can be used by translib test code as well as translib client test code (REST or telemetry) to verify end-to-end of all cases without depending on actual app modules or database state.
**- How to verify it**
Run …
=> Cleanup translib and cvl go test cases

tools/test/database_config.json, translib/db/db.go, translib/db/db_config.go, translib/db/db_test.go, translib/db/map.go, translib/db/subscribe.go, translib/db/test/testdb.go
* Added additional DBs
* NoDelete option used (Set|Mod)Entry
* MultiDB changes
* GetKeysByPattern(), Publish(), RunScript()
* DeleteKeys() bug fix
=> DB-Layer fixes/enhancements

cvl/schema/Makefile, cvl/testdata/schema/Makefile, go.mod, go.sum
1) Fixed pyang search paths in cvl schema makefiles to include top
models/yang/common directory. Without this pyang may not locate ietf
yangs during cvl schema builds, especially while building outside sonic
slave docker.
2) Updated go.mode and go.sum files to include new dependencies added
during recent cvl enhancemnts
=> Fix ietf yang search path for cvl schema builds

azure-pipelines.yml, debian/control, translib/db/db.go
Support to build in debian bullseye, the dh-systemd has removed and merged into debhelper.
Support to build by golang 1.15, fix the int type conversion error.
The change does not break the buster build, the first commit is good.
=> [Build]: Support to build in debian bullseye with golang 1.15

translib/acl_app.go, translib/api_tests_app.go, translib/app_interface.go, translib/common_app.go, translib/internal/apis/db_diff.go, translib/internal/apis/db_diff_test.go, translib/internal/apis/notify.go, translib/intf_app.go, translib/lldp_app.go, translib/pfm_app.go, translib/subscribe_app_interface.go, translib/subscribe_app_utils.go, translib/sys_app.go, translib/translib.go, translib/yanglib_app.go
Added new translateSubscribe() and processSubscribe() functions to appInterface as per HLD https://github.com/sonic-net/SONiC/pull/1287
Also added stub implementation of these functions to all existing app modules. It blindly treats all paths as non-db. Basic subscription features, without on_change, can be verified with this mapping.
=> AppInterface enhancements for subscription

models/yang/annotations/sonic-extensions.yang, patches/goyang/goyang.patch
Patch the goyang to support transformer infra memory usage enhancement using optimized yang schema loaded from ocbinds. 
Add annotations to the sonic extensions to support transformer infra translations.
Merge the PRs in this order to resolve build dependencies
1) Apply goyang patch xfmr memory optimization
2) Transformer infra enhancements and optimization changes PR#(https://github.com/sonic-net/sonic-mgmt-common/pull/80)
3) Unit Test for transformer infra. (test yang, callbacks, ut infra files, ut cases) PR# https://github.com/sonic-net/sonic-mgmt-common/pull/81
=> Apply goyang patch xfmr memory optimization

translib/ocbinds/schema.go, translib/request_binder.go, translib/transformer/xlate_to_db.go
Introduced a new function `ocbinds.GetSchema()`, which is equivalent of the generated function `ocbinds.Schema()`, but loads the schema only once. Translib request_binder and transformer components will use the new function. Avoids duplicate schema loads during init.
=> Avoid duplicate ocbinds schema loading

translib/db/db_cursor.go, translib/db/db_cursor_test.go, translib/tlerr/tlerr.go
Added following methods to scan and iterate the db entries using redis DB scan cursor.
- NewScanCursor() :  to create ScanCursor type to perform the GetNext.. operation
- GetNextKeys() : retrieves a few keys and returns true if the scan is complete.
- GetNextFields() : retrieves a few matching fields and returns true if the scan is complete.
- GetNextRedisKeys() : retrieves a few redisKeys and returns true if the scan is complete
Required for the subscription enhancements as described in HLD https://github.com/sonic-net/SONiC/pull/1287
=> DB Access:  DB scan cursor support for keys and fields to iterate it

translib/transformer/subscribe_req_xlate.go, translib/transformer/xfmr_interface.go, translib/transformer/xlate.go, translib/transformer/xlate_datastructs.go, translib/transformer/xspec.go, translib/utils/bits.go
Subscribe request translation API implementation for the common app module, to generically identify the mapped DB table, key and other related info for the given subscribe path request using the YANG model, annotations, and other callbacks.
Required for the subscription enhancements as described in HLD sonic-net/SONiC#1287
=> Subscribe request translation API implementation

translib/db/db.go, translib/db/db_onchangecache.go, translib/db/db_onchangecache_test.go, translib/tlerr/tlerr.go
1\) Introduced the OnChange cache in the DB object. Cache is maintained as map[string]db.Value, where map key is the redis key.
OnChange cache is not enabled by default. DB instance should be inited with IsEnableOnChange=true option and caching should be enabled for specific tables by calling DB.RegisterTableForOnChangeCaching(). DB.OnChangeCacheUpdate() and DB.OnChangeCacheDelete() functions should be used to refresh the cache contents.
2\) Enhanced DB.GetEntry() to return value from the OnChnage cahce if the key exists in the cache. Otherwise the value will be read from redis and cache will be updated.
Part of the subscription enhancements described in the HLD https://github.com/sonic-net/SONiC/pull/1287
=> DB Access: OnChange cache

translib/common_app.go, translib/transformer/subscribe_req_xlate.go, translib/transformer/subscribe_resp_xlate.go, translib/transformer/xconst.go
Subscribe response translation API implementation for the common app module, to generically translate the database table and key info into corresponding YANG list node key(s) using the YANG schema, annotations, path and key transformers if needed, and populate the converted YANG key into the list node's key value of the URI
Required for the subscription enhancements as described in HLD https://github.com/sonic-net/SONiC/pull/1287
=> Subscribe response translation API implementation for the common app module

cvl/cvl_api.go, cvl/cvl_cache.go, cvl/internal/yparser/yparser.go
=> Fix memleaks in cvl

translib/db/db.go, translib/db/db_test.go, translib/transformer/transformer_test.go, translib/transformer/xlate_utils.go, translib/translib.go
Translib DBAccess library defines ERROR_DB and USER_DB, which are not supported by the database docker. All REST or gNMI GET operation prints following warning logs.
```
E0619 06:17:57.258827      19 db.go:385] Invalid database number 3
I0619 06:17:57.258872      19 db.go:431] NewDB: Init indication not requested
W0619 06:17:57.258928      19 db.go:382] Database instance not present for the Db name: ERROR_DB
W0619 06:17:57.258960      19 db.go:382] Database instance not present for the Db name: USER_DB
```
Removed the invalid ERROR_DB and USER_DB DBNum definitions and their references. Also skipped creating db object for index 3 -- it used to be the LOGLEVEL_DB earlier, which has been retired now.
=> Remove invalid db type definitions: ERROR_DB, USER_DB

azure-pipelines.yml
* Download only the libyang.deb and sonic_yang_models.whl artifacts to save space
* Download artifacts from pipeline 142 in order to download from branch specific build
=> Download only required artifacts during pipeline build

cvl/Makefile, cvl/cvl.go, cvl/cvl_api.go, cvl/cvl_error_test.go, cvl/cvl_leafref_test.go, cvl/cvl_must_test.go, cvl/cvl_syntax.go, cvl/cvl_test.go, cvl/cvl_when_test.go, cvl/internal/util/util.go, cvl/internal/yparser/ly_path.go, cvl/internal/yparser/yparser.go, cvl/testdata/schema/sonic-acl.yang
Issue:
When cvl validation fails it returns a `CVLErrorInfo` object, which is supposed to indicate the errored table, key and field info with user defined error-message if any. But cvl is not filling all these details in most of the cases.
Example: creation of a ACL_RULE entry without the PACKET_ACTION field (which is mandatory) returns `CVLErrorInfo{TableName: "", ErrCode: 1003, CVLErrDetails: "Required Field is Missing", Keys: []string(nil), Value: "", Field: "", Msg: " with keys[] has field  with invalid value ", ConstraintErrMsg: "", ErrAppTag: ""}`. Error info does not indicate what actually failed.
Fix:
This PR fixes the cvl error reporting logic to return consistent error response when data validation fails. All syntax errors will have table, keys, and error message filled. A …
=> CVL error reporting enhancements

translib/transformer/xfmr_interface.go, translib/transformer/xlate_prune.go, translib/transformer/xlate_prune_acl_test.go, translib/transformer/xlate_prune_interfaces_test.go, translib/transformer/xlate_prune_ospf_test.go, translib/transformer/xlate_prune_radius_test.go, translib/transformer/xlate_prune_stats.go, translib/transformer/xlate_prune_test.go, translib/transformer/xlate_xfmr_handler.go
- Pruning API used by subtree transformers for Query Parameters.
- Tests. ( Only ACL is enabled currently, since the others need support from the corresponding feature teams )
- Updated the hooks to invoke the pruning API.
- The GET request cancelling context parameter is passed to some of the pruning functions, but is not implemented since that is appearing in a separate PR
=> Query Parameters Pruning API and Tests

translib/tlerr/app_errors.go
Introduce a AppTag field to all error types defined in `app_errors.go` file. This will be an optional value. Can be used an app specific error code by apps. REST or gNMI servers can copy them in protocol specific error fields, like RESTCONF `error-app-tag`. REST server will be enhanced in a separate PR after this PR is merged.
=> Add 'AppTag' in translib app errors

cvl/cvl_api.go, cvl/internal/util/util.go, translib/pfm_app.go, translib/transformer/testxfmryang_test.go, translib/transformer/xfmr_testxfmr_callbacks.go, translib/transformer/xlate_tbl_info.go
When LISTs were converted back to tables, there is a possibility of having consecutive duplicate table names in the result if there exists a dependency between table lists. Added a mechanism to remove such entries. More comments in the code for the next steps
=> Remove Duplicates in topsort results

tools/test/dbinit.py, tools/test/platform.json
Add dbinit.py script, which pupulates test data into the essential tables like PORT, PORT_TABLE, COUNTERS, DEVICE_METADATA etc. Helps to verify REST and gNMI get/set operations on the build server itself.
**These scripts are not installed to the sonic switch.**
=> Script to populate the test data to the simulator db

translib/transformer/subscribe_req_xlate.go
Change an unordered map traversal to an ordered array traversal to ensure correct ordering of fields within a DB key.
Addresses issue #126
=> Fix subscriptions for lists with multiple keys.

models/yang/Makefile, tools/pyang/lint, tools/pyang/pyang_plugins/strict_lint.py
Community's OC-linter's leaf mirror check is not working if state leaf is deleted using not-supported deviation because the checks in linter happens during pyang's reference stages. Ideal place to lint is post-validation.
- Added a ExtraCheckPlugin to handle missing or not-working checks from oc-linter.
- Updated oc-linter to LATEST. New checks related to siblings nodes are added.
=> Add leaf Mirror linter Check for not-supported deviation

cvl/internal/yparser/yparser.go, cvl/testdata/schema/sonic-cablelength.yang, cvl/testdata/schema/sonic-dscp-tc-map.yang, cvl/testdata/schema/sonic-pfc-priority-queue-map.yang, cvl/testdata/schema/sonic-tc-priority-group-map.yang, cvl/testdata/schema/sonic-tc-queue-map.yang, tools/pyang/pyang_plugins/sonic_linter.py
CVL relying on 2-key list to determine the mapping Instead it should rely on one key and one non-key leaf
Change-Id: Ia26cb5d3f7f760e7899aa625e7cfc7d3a1e83035
=> [JIRA SONIC-88436] - Disallow duplicate dyamic field names

cvl/cvl_api.go, cvl/cvl_test.go, cvl/testdata/schema/sonic-ospfv2.yang, cvl/testdata/schema/sonic-vlan-subinterface.yang, cvl/tools/generate_yin.py
When dependent target TABLE has multiple lists, if there exists a partial dependency, the loosely hanging LIST was causing sorting issue.
Below are the fix implemented
1. Retained the last LIST entry instead of first.
2. Injected dependency on all target LISTs of the TABLE.
=> CVL Sort issue in target TABLE with multi-list

cvl/internal/yparser/yparser.go
We detect a memory leak in sonic-mgmt-common.
Use C.free to release CString memory.
Run sonic-mgmt-common unit test.
=> Release CString memory to fix memory leak

models/yang/annotations/openconfig-interfaces-annot.yang, translib/transformer/xfmr_intf.go
**What I did:**
Added gNMI subscription transformer support for OpenConfig Ethernet Interfaces.
**Why I did it?**
Replacing existing intf_app.go code with transformer code.
**How did I verify the changes?**
Verified by manually testing gNMI subscription.
**Log files for gNMI subscription manual run:**
[UT logs community subscription ON change IPv4v6.docx](https://github.com/sonic-net/sonic-mgmt-common/files/15395754/UT.logs.community.subscription.ON.change.IPv4v6.docx)
[UT logs Community subscription SAMPLE IPv4v6.docx](https://github.com/sonic-net/sonic-mgmt-common/files/15395755/UT.logs.Community.subscription.SAMPLE.IPv4v6.docx)
[UT logs Community subscription TARGET DEFINED IPv4v6.docx](https://github.com/sonic-net/sonic-mgmt-common/files/15395756/UT.logs.Community.subscription.TARGET.D …
=> Adding subscription support for ethernet interfaces.

patches/goyang/goyang.patch, patches/ygot/ygot.patch
Prevent deadlocking on the ChildSchemaMutex by ensuring no other go routine is holding the lock while the Entry struct is copied.
=> Fix https://github.com/sonic-net/sonic-gnmi/issues/266

config/transformer/models_list, go.sum, models/yang/annotations/openconfig-interfaces-annot.yang, models/yang/extensions/openconfig-interfaces-deviation.yang, models/yang/sonic/import.mk, translib/transformer/portchannel_openconfig_test.go, translib/transformer/sw_portchannel.go, translib/transformer/xfmr_intf.go
Support for PortChannel at REST and subscription level along with test automation.
This support is limited to Static PortChannel
New file: translib/transformer/sw_portchannel.go
New Test File: translib/transformer/portchannel_openconfig_test.go
HLD Document: https://github.com/sonic-net/SONiC/pull/1727
TestApp Result: (Part of IPv4 and v6 tests fail locally as they are made to pass azure-pipeline tests which does not recognize STATE_DB)
[portchannel_testapp.log](https://github.com/user-attachments/files/15930834/portchannel_testapp.log)
Subscription Logs:
(At interface[name=PortChannel###]/config and interface[name=PortChannel###]/openconfig-if-aggregate level)
[on_change_config.log](https://github.com/user-attachments/files/15828040/on_change_config.log) …
=> PortChannel Interface Static Support - OpenConfig Yang

translib/subscribe_notify.go
Paths that have composite fields defined can react to changes for any of those DB fields. If more than one of those fields changes when processing an OnChange event, the framework will generate two updates to process. This leads to an error because the framework handles multiple updates differently.
Handling multiple updates occurs [here](https://github.com/sonic-net/sonic-mgmt-common/blob/b91a4df3bd0e4be97e67ab3f27b1826b1713afc5/translib/subscribe_notify.go#L748C3-L749C84). Eventually, [mergeYgotAtPath](https://github.com/sonic-net/sonic-mgmt-common/blob/b91a4df3bd0e4be97e67ab3f27b1826b1713afc5/translib/subscribe_notify.go#L751) is called and that function tries to cast the GoStruct for the leaf path to a ValidatedGoStruct. This returns an error.
The fix is to only generate 1 update for …
=> Fix dropped OnChange notifications for paths with composite fields

cvl/cvl_cust_validation_test.go, cvl/testdata/schema/sonic-spanning-tree.yang
This commit includes an example cvl custom validation to demonstrate its capability to allow/deny configuration based on other db data. CVL test schema for the STP table now includes a custom validation callback ValidateStpFeatureEnabled(), which accepts the config only if stp_supported=true in the APPL_DB table "SWITCH_TABLE:switch". This function is compiled & run only during cvl gotest execution. Not used in the production REST or telemetry server.
=> CVL custom validation example and test case

cvl/cvl_api.go, cvl/cvl_test.go, cvl/testdata/schema/sonic-pki.yang, cvl/testdata/schema/sonic-sample-global.yang, cvl/testdata/schema/sonic-security-global.yang
- When singleton table has a leafref to non-sigleton containers, then delete validation was catching in-instance error. Fixed the issue.
=> Fix Delete Validation for singleton lists

models/yang/annotations/sonic-extensions.yang, translib/common_app.go, translib/db/db.go, translib/db/db_config.go, translib/transformer/test/openconfig-test-xfmr-annot.yang, translib/transformer/test/openconfig-test-xfmr.yang, translib/transformer/test/sonic-test-xfmr.yang, translib/transformer/testxfmryang_test.go, translib/transformer/xfmr_interface.go, translib/transformer/xfmr_intf.go, translib/transformer/xfmr_testxfmr_callbacks.go, translib/transformer/xlate.go, translib/transformer/xlate_datastructs.go, translib/transformer/xlate_del_to_db.go, translib/transformer/xlate_from_db.go, translib/transformer/xlate_to_db.go, translib/transformer/xlate_utils.go, translib/transformer/xlate_xfmr_handler.go, translib/transformer/xspec.go
This enhancement to the transformer component in management framework will support DELETE operations using OpenConfig YANG models, enabling configuration data deletion through YANG data tree traversal.
Refer - https://github.com/sonic-net/SONiC/pull/1950  for more details.
The DELETE operation will remove data resources under the specified target resource, identified by the RESTCONF target resource URI, which can be at any depth within a YANG data model.
Previously, deleting data resources with the DELETE operation at any depth of a YANG model was challenging, and support was limited to removing the target resource, not the hierarchy beneath it. This feature aims to address this issues by supporting DELETE operation at any YANG depth.
This enhancement will be the base or prerequisite for …
=> model based delete handling in transformer infra for openconfig yangs

translib/common_app.go, translib/transformer/testxfmryang_test.go, translib/transformer/xfmr_testxfmr_callbacks.go, translib/transformer/xlate.go, translib/transformer/xlate_datastructs.go, translib/transformer/xlate_del_to_db.go, translib/transformer/xlate_from_db.go, translib/transformer/xlate_replace_utils.go, translib/transformer/xlate_to_db.go, translib/transformer/xlate_utils.go, translib/transformer/xspec.go
This enhancement to the transformer component in management framework will support REPLACE/PUT operation using OpenConfig YANG models, enabling configuration data replacement through YANG data tree traversal.
Refer - [sonic-net/SONiC#1950](https://github.com/sonic-net/SONiC/pull/1950) for more details.
The PUT/REPLACE RESTCONF method, equivalent to the NETCONF “create” or “replace” operations, can create non-existing data resources or replace existing ones, with the request payload, for a specified resource, identified by the RESTCONF target resource URI.
Previously, replacing data resources with the PUT/REPLACE operation at any depth of a YANG model was challenging, and support was limited to replacing only the data translated from the request payload rather than the entire data …
=> model based replace/put operation handling in transformer infra for openconfig yangs
